let randomNumber=parseInt(Math.random()*100+1);

const submit=document.querySelector('#subt')  //selected submit button for handling click event eventListener.
const userInput=document.querySelector('#guessField') //selected userinput field
const guessSlot=document.querySelector('.guesses') //selected previous guesses slot
const remaining=document.querySelector('.remaining')//selected remaining guesses number
const lowOrHi=document.querySelector('.lowOrHi')//selected the random no generated by computer is low or high
const startOver=document.querySelector('.resultParas')//when all the 10 guesses are over then we have to perform some task that is start over so we hav selected for that reason.

const b=document.createElement('button')// we have to insert paragraph somewhere in the future so we took it here.(may be used to display low or high)

let prevGuess=[]//to store the array of prev guesses so that user dont repeate guesses atleast
let numGuess=1 //to count the no of guesses.

let playGame=true//it allows us to play the game. and will be disabled after the 10 guesses.



if(playGame){
    submit.addEventListener('click',function(e){
        e.preventDefault()//dont take values to server i will handle it..
        const guess=parseInt(userInput.value)
        validateGuess(guess)//passing the guess to validate fun
    })
}

function validateGuess(guess){

//it is used to varify that the no entered by user is in range of 1 to 100 or not. whether it is a negative more than 100 are eliminated.

if(isNaN(guess)){
    alert('Please Enter a Valid Number');
}
else if(guess<1){
    alert('Please Enter a Number greater than 0');

}
else if(guess>100){
    alert('Please Enter a Number less than 100');

}
else{
  prevGuess.push(guess) 
  
  if(numGuess===10){
    displayGuess(guess)
    dispalyMessage(` Game Over. Random Number Was ${randomNumber}`)
    endGame()
  }
  else{
    displayGuess(guess)
    chkGuess(guess)
  }
}

    


}

function chkGuess(guess){

    //this fun is for checking whether the user guess matches with the random no or not if it matches then user won.it also suggest user high or low


    if(guess===randomNumber){
        dispalyMessage(`You guessed it right`)
        endGame();

    }
    else if(guess<randomNumber){
        dispalyMessage(`your guess is low`)

    }
    else if(guess>randomNumber){
        dispalyMessage(`your guess is high`)

    }
}


function displayGuess(guess){

    //it will clean the value after each guess.and updates the array of prev guesses and remaininng no of guesses.
    userInput.value=''// clean the value after each submit.
    guessSlot.innerHTML+=`${guess}  `// adds the guess each time keeping prev list of guesses.
    numGuess++
    remaining.innerHTML=`${11-numGuess}`
}


function dispalyMessage(message){

    //used to interect with dom. add the innertec=xt and display the message and othr things.
    lowOrHi.innerHTML=`<h2>${message}</h2>`
}

function endGame(){
    userInput.value=''
    userInput.setAttribute('disabled','')
    b.classList.add('button')
    b.innerHTML=`<h2 id="newGame">Start New Game</h2>`
    startOver.appendChild(b)
    playGame=false
    newGame()
}

function newGame(){
    const newGameButton=document.querySelector('#newGame')
    newGameButton.addEventListener('click',function(e){
        randomNumber=parseInt(Math.random()*100+1);
        prevGuess=[]
        numGuess=1
        guessSlot.innerHTML=''
        remaining.innerHTML=remaining.innerHTML=`${11-numGuess}`
        userInput.removeAttribute('disabled')
        startOver.removeChild(b)
        playGame=true
    })

}

